version: '3.7'

services:
  frontend:
    build:
      context: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    container_name: frontend
    ports:
      - 3000:3000
    depends_on: 
      - backend
  backend:
    build:
      context: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    container_name: backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model:ro
    depends_on: 
      - training
  training:
    build:
      context: https://github.com/docker-hy/ml-kurkkumopo-training.git
    container_name: training
    volumes:
      - imgs:/src/imgs
      - model:/src/model
    
volumes:
  imgs:
  model: