# Version must be >3.2 for extended notation
# See more at https://github.com/docker/compose/issues/4763
version: '3.7' 

services: 
    ex2_1:
      image: devopsdockeruh/first_volume_exercise
      volumes:
        - type: bind
          source: ./logs.txt
          target: /usr/app/logs.txt
      container_name: ex2_1