name: exercise3_2

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: part3/exercise2
    steps:
      - uses: actions/checkout@v2
      - name: Login Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Dockerfile
        run: docker build -t frontend .
      - name: Add tags
        run: |
          docker tag frontend ${{ secrets.DOCKER_USERNAME }}/deploy-exercise
          docker tag frontend registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/deploy-exercise
      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Push to Heroku
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
